### ISSUE TITLE
Introduce a "Forward Agent String" option

### ISSUE THREAD

**Issue by derdiggn** [restinthemiddle/restinthemiddle#22]
In some cases we need to pass the Agent String from the Requesting Browser / Device.

In our case we have a unsupported browser switch based on the agent string, this is accully not working behind rest-in-the-middle.

**Comment by jensschulze** [comment]
Resolved in [#e1184a47](https://github.com/restinthemiddle/restinthemiddle/commit/e1184a47f4fe6bef315a4e1f9f925993f036b798): Restinthemiddle does not set a User-Agent string itself by default.
